
services:
  app:
    build: .    
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
    driver: bridge